name: KiwiRank
version: 1.1.0
main: ee.winni.kiwirank.Rank
commands:
  setrank:
    description: 设置等级
    usage: /setrank Lawaxi vip
  addexp:
    description: 添加经验
    usage: /addexp Lawaxi 100
  level:
    description: 查询当前等级
    usage: /level 玩家名(可省略)